'use client'

import { useEffect, useRef, type FormEvent } from 'react'
import { useRouter } from 'next/navigation'
import { gsap, EASE, rem } from '@/lib/motion-v4'

/**
 * THE SERVICES HUB'S HERO — THE CROWD (2026-09-18, user: "it's too
 * playful and too much, with too much unnecessary motion. The motion I
 * like is scroll motion… it would be cool to have a background image").
 * It replaces THE BRIEF (HubAgent.tsx: the agent's cursor building the
 * page, the skeletons, the plan's chips ticking, the three product
 * cards, the dot field, the asks typing themselves — all parked,
 * unimported, with their rules in hub.css).
 *
 * THE PICTURE is the user's own (chosen from five concepts I wrote
 * prompts for, and generated by them): a crowd of people smeared by a
 * long exposure on a pale, almost white ground, and ONE figure standing
 * perfectly still and sharp, right of centre. It is the page's argument
 * — six services, one outcome: be the one they remember — and it is the
 * house world already (the about page's crows: black on off-white,
 * motion blur, air). public/services/crowd-*.webp, greyscale, 1916x821.
 *
 * THE FRAME. The picture is full bleed, anchored to its foot so the
 * crowd band sits low and the empty sky fills the top; the statement
 * stands in that sky, left, clear of the still figure. The prompt sits
 * at the foot — the same real form as before (the router sends a brief
 * to the service page that answers it, or to /contact), now STILL: no
 * cursor, no typing, no chips ticking.
 *
 * THE MOTION IS THE SCROLL, and nothing else:
 *   · ON LOAD, once: the picture resolves — blur and a breath of scale
 *     off — and the lines rise through their masks. One pass, no loop.
 *   · ON SCROLL: the picture eases from 1.06 to 1 and drifts up at a
 *     fraction of the hand (it is sticky, so the drift is depth); the
 *     statement climbs faster and dims; the still figure holds the
 *     centre while the crowd goes by. The bench then covers it all
 *     (`--sh-cover`, written by HubBench as before).
 * Nothing breathes, spins, ticks or types.
 *
 * THE DRIVER. One gsap.ticker, one rect a frame; everything written is
 * a transform, an opacity or a blur on two elements. Reduced motion and
 * no JS get the landed frame: the picture sharp, the words up, the
 * prompt ready.
 */

/** THE ROUTER: what the words of a brief point at, first match wins
 *  (HubAgent's own list, unchanged) */
const NEEDS: [RegExp, string][] = [
  [/seo|google|rank|search|found|traffic|visib/i, '/services/seo'],
  [/3d|immersive|webgl|three\.?js|experience/i, '/services/3d-websites'],
  [/redesign|rebuild|refresh|dated|old site|slow/i, '/services/website-redesign'],
  [/one[\s-]?page|landing|single page/i, '/services/one-page-websites'],
  [/develop|code|shop|store|commerce|app|cms|integrat|fast|build/i, '/services/web-development'],
  [/design|brand|look|beautiful|remember|ui|ux/i, '/services/web-design'],
]

/** the scroll's reach, in viewport heights: the picture lands by then */
const REACH = 0.9
/** the picture: its scale at rest and how far it drifts up (svh) */
const ZOOM = 1.06
const DRIFT = 5
/** the statement's climb (svh) and how far it dims */
const CLIMB = 11
const DIM = 0.55

const clamp01 = (v: number) => (v < 0 ? 0 : v > 1 ? 1 : v)

export default function HubStill({ kicker, statement }: { kicker: string; statement: readonly string[] }) {
  const ref = useRef<HTMLElement | null>(null)
  const router = useRouter()

  const onSubmit = (e: FormEvent<HTMLFormElement>) => {
    const form = e.currentTarget
    const brief = String(new FormData(form).get('brief') ?? '').trim()
    e.preventDefault()
    if (!brief) {
      form.querySelector<HTMLInputElement>('.hc-input')?.focus()
      return
    }
    const hit = NEEDS.find(([re]) => re.test(brief))
    form.classList.add('is-routing')
    const to = hit ? hit[1] : `/contact?brief=${encodeURIComponent(brief)}`
    window.setTimeout(() => router.push(to), 560)
  }

  useEffect(() => {
    const hero = ref.current
    if (!hero) return
    const pic = hero.querySelector<HTMLElement>('.hc-pic')!
    const body = hero.querySelector<HTMLElement>('.hc-body')!
    const lines = Array.from(hero.querySelectorAll<HTMLElement>('.hc-ln'))
    const reduce = window.matchMedia('(prefers-reduced-motion: reduce)').matches

    if (reduce) {
      hero.classList.add('is-in')
      return () => hero.classList.remove('is-in')
    }

    /* ON LOAD, once: the picture resolves, the lines rise */
    const ent = { v: 0 }
    gsap.set(lines, { yPercent: 115 })
    const tl = gsap.timeline()
    tl.call(() => hero.classList.add('is-in'), undefined, 0)
    tl.to(ent, { v: 1, duration: 1.7, ease: EASE.glass }, 0)
    tl.to(lines, { yPercent: 0, duration: 1.15, ease: EASE.glass, stagger: 0.1 }, 0.25)

    /* ON SCROLL: the picture settles and drifts, the words climb */
    let wrote = -1
    const tick = () => {
      const vh = window.innerHeight
      const p = clamp01(window.scrollY / (vh * REACH))
      const e = ent.v
      if (Math.abs(p - wrote) < 0.0005 && e >= 1) return
      wrote = p
      const k = rem()
      /* the resolve: the load's blur and the scroll's settle share one scale */
      const scale = 1 + (ZOOM - 1) * (1 - p) + 0.06 * (1 - e)
      const blur = 16 * (1 - e) * (1 - e)
      pic.style.transform = `translate3d(0, ${(-p * DRIFT * vh) / 100}px, 0) scale(${scale.toFixed(4)})`
      pic.style.filter = blur > 0.05 ? `blur(${(blur * k).toFixed(2)}px)` : ''
      pic.style.opacity = clamp01(e * 1.8).toFixed(3)
      body.style.transform = `translate3d(0, ${(-p * CLIMB * vh) / 100}px, 0)`
      body.style.opacity = (1 - p * DIM).toFixed(3)
    }
    tick()
    gsap.ticker.add(tick)

    return () => {
      tl.kill()
      gsap.ticker.remove(tick)
      hero.classList.remove('is-in')
      ;[pic, body, ...lines].forEach((el) => el.removeAttribute('style'))
    }
  }, [])

  return (
    <header ref={ref} className="sh-hero hc">
      {/* THE PICTURE — the page's argument, and decoration: the words
          below say it in text */}
      <div className="hc-pic" aria-hidden="true">
        <img
          src="/services/crowd-1920.webp"
          srcSet="/services/crowd-900.webp 900w, /services/crowd-1400.webp 1400w, /services/crowd-1920.webp 1920w"
          sizes="100vw"
          alt=""
          width={1916}
          height={821}
          fetchPriority="high"
          decoding="async"
          draggable={false}
        />
      </div>

      <div className="hc-body">
        <p className="sh-kicker hc-kicker hc-ent">{kicker}</p>
        <h1 className="hc-state">
          {statement.map((ln, i) => (
            <span key={i} className="hc-mask">
              <span className="hc-ln">
                {ln}
                {i < statement.length - 1 ? ' ' : ''}
              </span>
            </span>
          ))}
        </h1>

        {/* THE PROMPT: the same real form — the router answers it; without
            JS it is a GET to /contact */}
        <form className="hc-prompt hc-ent" action="/contact" method="get" onSubmit={onSubmit} role="search" aria-label="Tell us what you need">
          <svg className="hc-spark" viewBox="0 0 24 24" aria-hidden="true">
            <path d="M12 2.5l1.9 6.1a2 2 0 0 0 1.4 1.4l6.2 2-6.2 2a2 2 0 0 0-1.4 1.4L12 21.5l-1.9-6.1a2 2 0 0 0-1.4-1.4l-6.2-2 6.2-2a2 2 0 0 0 1.4-1.4z" fill="currentColor" />
          </svg>
          <input className="hc-input" name="brief" type="text" autoComplete="off" placeholder="Tell us what you need" aria-label="Tell us what you need" maxLength={160} />
          <button className="hc-send" type="submit" aria-label="Send">
            <svg viewBox="0 0 24 24" aria-hidden="true">
              <path d="M5 12h13M12.5 6l6 6-6 6" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
          </button>
        </form>
      </div>
    </header>
  )
}
