/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ArticleImage = {
  _type: "articleImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
};

export type ArticleNote = {
  _type: "articleNote";
  title?: string;
  text?: string;
};

export type ArticleStats = {
  _type: "articleStats";
  items?: Array<{
    value?: string;
    label?: string;
    _type: "statistic";
    _key: string;
  }>;
};

export type ArticleTable = {
  _type: "articleTable";
  caption?: string;
  head?: Array<string>;
  rows?: Array<{
    cells?: Array<string>;
    _type: "tableRow";
    _key: string;
  }>;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: AuthorReference;
  published?: string;
  updated?: string;
  topic?: string;
  excerpt?: string;
  cover?: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    position?: string;
    _type: "image";
  };
  answer?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & ArticleTable)
    | ({
        _key: string;
      } & ArticleStats)
    | ({
        _key: string;
      } & ArticleNote)
    | ({
        _key: string;
      } & ArticleImage)
  >;
  metaTitle?: string;
  description?: string;
  service?: {
    slug?:
      | "web-design"
      | "web-development"
      | "3d-websites"
      | "one-page-websites"
      | "website-redesign"
      | "seo";
    label?: string;
    line?: string;
  };
  studies?: Array<string>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  siteKey?: "konstantinos" | "nabil";
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | ArticleImage
  | ArticleNote
  | ArticleStats
  | ArticleTable
  | AuthorReference
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Author
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../KONA/src/sanity/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(published desc, _createdAt desc) {  _id, title, "slug": slug.current, metaTitle, description, excerpt, topic,  published, updated, "author": author->siteKey, answer, service, studies,  cover{..., "width": asset->metadata.dimensions.width, "height": asset->metadata.dimensions.height},  body[]{..., _type == "articleImage" => {    ..., "width": asset->metadata.dimensions.width, "height": asset->metadata.dimensions.height  }}}
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  metaTitle: string | null;
  description: string | null;
  excerpt: string | null;
  topic: string | null;
  published: string | null;
  updated: string | null;
  author: "konstantinos" | "nabil" | null;
  answer: string | null;
  service: {
    slug?:
      | "3d-websites"
      | "one-page-websites"
      | "seo"
      | "web-design"
      | "web-development"
      | "website-redesign";
    label?: string;
    line?: string;
  } | null;
  studies: Array<string> | null;
  cover: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    position?: string;
    _type: "image";
    width: number | null;
    height: number | null;
  } | null;
  body: Array<
    | {
        _key: string;
        _type: "articleImage";
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        width: number | null;
        height: number | null;
      }
    | {
        _key: string;
        _type: "articleNote";
        title?: string;
        text?: string;
      }
    | {
        _key: string;
        _type: "articleStats";
        items?: Array<{
          value?: string;
          label?: string;
          _type: "statistic";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "articleTable";
        caption?: string;
        head?: Array<string>;
        rows?: Array<{
          cells?: Array<string>;
          _type: "tableRow";
          _key: string;
        }>;
      }
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
  > | null;
}>;

// Source: ../KONA/src/sanity/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0] {  _id, title, "slug": slug.current, metaTitle, description, excerpt, topic,  published, updated, "author": author->siteKey, answer, service, studies,  cover{..., "width": asset->metadata.dimensions.width, "height": asset->metadata.dimensions.height},  body[]{..., _type == "articleImage" => {    ..., "width": asset->metadata.dimensions.width, "height": asset->metadata.dimensions.height  }}}
export type POST_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  metaTitle: string | null;
  description: string | null;
  excerpt: string | null;
  topic: string | null;
  published: string | null;
  updated: string | null;
  author: "konstantinos" | "nabil" | null;
  answer: string | null;
  service: {
    slug?:
      | "3d-websites"
      | "one-page-websites"
      | "seo"
      | "web-design"
      | "web-development"
      | "website-redesign";
    label?: string;
    line?: string;
  } | null;
  studies: Array<string> | null;
  cover: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    position?: string;
    _type: "image";
    width: number | null;
    height: number | null;
  } | null;
  body: Array<
    | {
        _key: string;
        _type: "articleImage";
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        width: number | null;
        height: number | null;
      }
    | {
        _key: string;
        _type: "articleNote";
        title?: string;
        text?: string;
      }
    | {
        _key: string;
        _type: "articleStats";
        items?: Array<{
          value?: string;
          label?: string;
          _type: "statistic";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "articleTable";
        caption?: string;
        head?: Array<string>;
        rows?: Array<{
          cells?: Array<string>;
          _type: "tableRow";
          _key: string;
        }>;
      }
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
  > | null;
} | null;

// Source: ../KONA/src/sanity/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)]{"slug": slug.current}
export type POST_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "post" && defined(slug.current)] | order(published desc, _createdAt desc) {\n  _id, title, "slug": slug.current, metaTitle, description, excerpt, topic,\n  published, updated, "author": author->siteKey, answer, service, studies,\n  cover{..., "width": asset->metadata.dimensions.width, "height": asset->metadata.dimensions.height},\n  body[]{..., _type == "articleImage" => {\n    ..., "width": asset->metadata.dimensions.width, "height": asset->metadata.dimensions.height\n  }}\n}': POSTS_QUERY_RESULT;
    '*[_type == "post" && slug.current == $slug][0] {\n  _id, title, "slug": slug.current, metaTitle, description, excerpt, topic,\n  published, updated, "author": author->siteKey, answer, service, studies,\n  cover{..., "width": asset->metadata.dimensions.width, "height": asset->metadata.dimensions.height},\n  body[]{..., _type == "articleImage" => {\n    ..., "width": asset->metadata.dimensions.width, "height": asset->metadata.dimensions.height\n  }}\n}': POST_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current)]{"slug": slug.current}': POST_SLUGS_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
