/**
 * DIGIT OUTLINES for section 7's rail — extracts '0'..'9' from Manrope
 * ExtraLight (the numerals' own face and weight: --w-light = 200) as SVG
 * path data, baseline-normalised, and writes them to
 * src/components/v4/digit-paths.ts.
 *
 * WHY OUTLINES AT ALL: the rail's comet has to run along the digits' own
 * edges, and a stroke can only follow a PATH — DOM text has no edges to
 * give it. So the rail's numerals are "flattened" to paths and the same
 * geometry serves both jobs: filled once (with the fade-out gradient),
 * stroked three times (the comet's head and tail).
 *
 * Source: @fontsource/manrope's static latin 200 woff (opentype.js reads
 * woff; woff2 it does not). Fontsource ships Google's own builds, so
 * these outlines match what next/font renders to the pixel.
 *
 * Usage: node tools/glyphs.js
 */
const opentype = require('opentype.js')
const fs = require('fs')
const path = require('path')

const SRC = path.join(
  __dirname,
  '..',
  'node_modules',
  '@fontsource',
  'manrope',
  'files',
  'manrope-latin-200-normal.woff',
)
const OUT = path.join(__dirname, '..', 'src', 'components', 'v4', 'digit-paths.ts')

const buf = fs.readFileSync(SRC)
const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength))
const upem = font.unitsPerEm

const digits = {}
for (const ch of '0123456789') {
  const glyph = font.charToGlyph(ch)
  // baseline at y = upem: path coords land in [~0 .. upem] y-down, so one
  // shared viewBox `0 0 advance upem` frames every digit
  const p = glyph.getPath(0, upem, upem)
  digits[ch] = {
    d: p.toPathData(2),
    advance: Math.round((glyph.advanceWidth / upem) * 1000) / 1000,
  }
}

const body = `/**
 * GENERATED by tools/glyphs.js — do not edit by hand.
 * Manrope ExtraLight (200) digit outlines, from @fontsource/manrope's
 * static latin woff. Coordinates are y-down SVG space with the baseline
 * at y = ${upem}; advance widths are in 1/1000 em. Regenerate with
 * \`node tools/glyphs.js\` if the face or weight ever changes.
 */
export const UPEM = ${upem}
export const DIGITS: Record<string, { d: string; advance: number }> = ${JSON.stringify(digits, null, 2)}
`
fs.writeFileSync(OUT, body)
console.log('wrote', OUT, 'upem', upem, 'digits', Object.keys(digits).join(''))
